In [1]:
import pandas as pd
import numpy as np

## Datatypes and Attributes

In [2]:
# numpy's main datatype is nparray [nd array]
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1,2,3],
              [4,5,6.5]])
a2

array([[1. , 2. , 3. ],
       [4. , 5. , 6.5]])

In [5]:
a1.shape

(3,)

In [6]:
a2.shape

(2, 3)

In [7]:
#ndimensions
a1.ndim, a2.ndim

(1, 2)

In [8]:
a1.dtype, a2.dtype

(dtype('int32'), dtype('float64'))

In [9]:
a1.size, a2.size

(3, 6)

In [10]:
type(a1), type(a2)

(numpy.ndarray, numpy.ndarray)

In [11]:
# Creating Dataframe from a Numpy array
df = pd.DataFrame(a2)

In [12]:
df

0    1    2
0  1.0  2.0  3.0
1  4.0  5.0  6.5

## 2.Creating arrays

In [13]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [14]:
sample_array.dtype

dtype('int32')

In [15]:
ones = np.ones((2,3))

In [16]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [17]:
ones.dtype

dtype('float64')

In [18]:
type(ones)

numpy.ndarray

In [19]:
zeros = np.zeros((2,3))

In [20]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [21]:
zeros.dtype

dtype('float64')

In [22]:
range_array = np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [23]:
random_array = np.random.randint(0,10,size=(3,5))

In [24]:
random_array

array([[4, 4, 0, 3, 7],
       [8, 1, 3, 1, 4],
       [7, 3, 9, 1, 8]])

In [25]:
random_array.size

15

In [26]:
random_array.shape

(3, 5)

In [27]:
random_array_2 = np.random.random((5,3))
random_array_2

array([[0.10268402, 0.13846897, 0.12900988],
       [0.41392712, 0.27664247, 0.06359399],
       [0.6620687 , 0.68188585, 0.09179127],
       [0.61885882, 0.81091867, 0.74222164],
       [0.86930513, 0.96678822, 0.36216124]])

In [28]:
random_array_2.shape

(5, 3)

In [29]:
random_array_3 = np.random.rand(5,3)
random_array_3

array([[0.95495305, 0.90227717, 0.67084026],
       [0.72367471, 0.0157353 , 0.63134384],
       [0.40961484, 0.61662785, 0.1056441 ],
       [0.49628201, 0.54800784, 0.44975129],
       [0.25341639, 0.67203083, 0.16118519]])

In [30]:
random_array_3.shape

(5, 3)

In [31]:
#Psuedo random numbers
#np.random.seed()

In [32]:
np.random.seed(seed=0)
random_array_4 = np.random.randint(10, size=(5,3))
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [33]:
random_array_4.shape

(5, 3)

In [34]:
random_array_5 = np.random.random((5,3))
random_array_5

array([[0.79172504, 0.52889492, 0.56804456],
       [0.92559664, 0.07103606, 0.0871293 ],
       [0.0202184 , 0.83261985, 0.77815675],
       [0.87001215, 0.97861834, 0.79915856],
       [0.46147936, 0.78052918, 0.11827443]])

## 3.Viewing arrays and Matrices

In [35]:
np.unique(random_array_4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
a1

array([1, 2, 3])

In [37]:
a2

array([[1. , 2. , 3. ],
       [4. , 5. , 6.5]])

In [38]:
a1[0]

1

In [39]:
a2[0]

array([1., 2., 3.])

In [40]:
a2[:2,:2]

array([[1., 2.],
       [4., 5.]])

In [41]:
a3 = np.random.randint(10, size=(2,3,3))
a4 = np.random.randint(10, size=(2,3,4,5))

In [42]:
a3

array([[[0, 1, 9],
        [9, 0, 4],
        [7, 3, 2]],

       [[7, 2, 0],
        [0, 4, 5],
        [5, 6, 8]]])

In [43]:
a4

array([[[[4, 1, 4, 9, 8],
         [1, 1, 7, 9, 9],
         [3, 6, 7, 2, 0],
         [3, 5, 9, 4, 4]],

        [[6, 4, 4, 3, 4],
         [4, 8, 4, 3, 7],
         [5, 5, 0, 1, 5],
         [9, 3, 0, 5, 0]],

        [[1, 2, 4, 2, 0],
         [3, 2, 0, 7, 5],
         [9, 0, 2, 7, 2],
         [9, 2, 3, 3, 2]]],


       [[[3, 4, 1, 2, 9],
         [1, 4, 6, 8, 2],
         [3, 0, 0, 6, 0],
         [6, 3, 3, 8, 8]],

        [[8, 2, 3, 2, 0],
         [8, 8, 3, 8, 2],
         [8, 4, 3, 0, 4],
         [3, 6, 9, 8, 0]],

        [[8, 5, 9, 0, 9],
         [6, 5, 3, 1, 8],
         [0, 4, 9, 6, 5],
         [7, 8, 8, 9, 2]]]])

In [44]:
a4.shape

(2, 3, 4, 5)

In [45]:
a4[:,:,:,:4]

array([[[[4, 1, 4, 9],
         [1, 1, 7, 9],
         [3, 6, 7, 2],
         [3, 5, 9, 4]],

        [[6, 4, 4, 3],
         [4, 8, 4, 3],
         [5, 5, 0, 1],
         [9, 3, 0, 5]],

        [[1, 2, 4, 2],
         [3, 2, 0, 7],
         [9, 0, 2, 7],
         [9, 2, 3, 3]]],


       [[[3, 4, 1, 2],
         [1, 4, 6, 8],
         [3, 0, 0, 6],
         [6, 3, 3, 8]],

        [[8, 2, 3, 2],
         [8, 8, 3, 8],
         [8, 4, 3, 0],
         [3, 6, 9, 8]],

        [[8, 5, 9, 0],
         [6, 5, 3, 1],
         [0, 4, 9, 6],
         [7, 8, 8, 9]]]])

## 4.Manipulating and Comparing Arrays

### Arithmetic

In [46]:
a1

array([1, 2, 3])

In [47]:
a2

array([[1. , 2. , 3. ],
       [4. , 5. , 6.5]])

In [48]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [49]:
a1 + ones

array([2., 3., 4.])

In [50]:
a1 - ones

array([0., 1., 2.])

In [51]:
a1 * ones

array([1., 2., 3.])

In [52]:
a2

array([[1. , 2. , 3. ],
       [4. , 5. , 6.5]])

In [53]:
a1 * a2

array([[ 1. ,  4. ,  9. ],
       [ 4. , 10. , 19.5]])

In [54]:
# how can you reshape a2 to be compatible to a3
np.dot(a2,a3)

array([[[39. , 10. , 23. ],
        [22. , 28. , 34. ]],

       [[90.5, 23.5, 69. ],
        [60.5, 67. , 77. ]]])

In [55]:
a1 / ones

array([1., 2., 3.])

In [56]:
# // to remove decimals
a1 // ones

array([1., 2., 3.])

In [57]:
a2 ** 2

array([[ 1.  ,  4.  ,  9.  ],
       [16.  , 25.  , 42.25]])

In [58]:
a2 % 2

array([[1. , 0. , 1. ],
       [0. , 1. , 0.5]])

In [59]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [60]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])

### Aggregation
Aggregation = performing the same operation on a number of things

In [61]:
listy = [1,2,3]
type(listy)

list

In [62]:
sum(listy)

6

In [63]:
np.mean(a2)

3.5833333333333335

In [64]:
np.max(a2)

6.5

In [65]:
#standard Deviation = a measure of how spread out a group of numbers is from mean
np.std(a2)

1.8352262954621035

In [66]:
np.min(a2)

1.0

In [67]:
# Variance =  measure of the average degree to which each number is different to the mean
#high Variance wider range of number
#lower Variance lower range of number
np.var(a2)

3.368055555555556

In [68]:
# standard deviation is sq of varaince
np.sqrt(np.var(a2))

1.8352262954621035