In [1]:
import pandas as pd
import numpy as np

## Datatypes and Attributes

In [2]:
# numpy's main datatype is nparray [nd array]
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1,2,3],
              [4,5,6.5]])
a2

array([[1. , 2. , 3. ],
       [4. , 5. , 6.5]])

In [5]:
a1.shape

(3,)

In [6]:
a2.shape

(2, 3)

In [7]:
#ndimensions
a1.ndim, a2.ndim

(1, 2)

In [8]:
a1.dtype, a2.dtype

(dtype('int32'), dtype('float64'))

In [9]:
a1.size, a2.size

(3, 6)

In [10]:
type(a1), type(a2)

(numpy.ndarray, numpy.ndarray)

In [11]:
# Creating Dataframe from a Numpy array
df = pd.DataFrame(a2)

In [12]:
df

0    1    2
0  1.0  2.0  3.0
1  4.0  5.0  6.5

## 2.Creating arrays

In [13]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [14]:
sample_array.dtype

dtype('int32')

In [15]:
ones = np.ones((2,3))

In [16]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [17]:
ones.dtype

dtype('float64')

In [18]:
type(ones)

numpy.ndarray

In [19]:
zeros = np.zeros((2,3))

In [20]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [21]:
zeros.dtype

dtype('float64')

In [22]:
range_array = np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [23]:
random_array = np.random.randint(0,10,size=(3,5))

In [24]:
random_array

array([[9, 0, 1, 9, 7],
       [1, 9, 0, 7, 5],
       [8, 5, 1, 3, 4]])

In [25]:
random_array.size

15

In [26]:
random_array.shape

(3, 5)

In [27]:
random_array_2 = np.random.random((5,3))
random_array_2

array([[0.67775715, 0.96728612, 0.88131636],
       [0.6532347 , 0.43992974, 0.94959258],
       [0.40691881, 0.37960716, 0.96762815],
       [0.17021886, 0.92675483, 0.80291152],
       [0.7375243 , 0.4562906 , 0.26010312]])

In [28]:
random_array_2.shape

(5, 3)

In [29]:
random_array_3 = np.random.rand(5,3)
random_array_3

array([[0.44817638, 0.39417725, 0.55870995],
       [0.63843455, 0.15244976, 0.79459496],
       [0.20143015, 0.42791226, 0.41915613],
       [0.74913173, 0.89493663, 0.88293497],
       [0.13368936, 0.52412954, 0.43768453]])

In [30]:
random_array_3.shape

(5, 3)

In [31]:
#Psuedo random numbers
#np.random.seed()

In [32]:
np.random.seed(seed=0)
random_array_4 = np.random.randint(10, size=(5,3))
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [33]:
random_array_4.shape

(5, 3)

In [35]:
random_array_5 = np.random.random((5,3))
random_array_5

array([[0.79172504, 0.52889492, 0.56804456],
       [0.92559664, 0.07103606, 0.0871293 ],
       [0.0202184 , 0.83261985, 0.77815675],
       [0.87001215, 0.97861834, 0.79915856],
       [0.46147936, 0.78052918, 0.11827443]])